### ISSUE TITLE
Allow peer dependency of React v15

### ISSUE THREAD

**Issue by justinanastos** [reactjs/react-static-container#2]
This is a dependency of [react-relay v0.7.3](https://github.com/facebook/relay/releases/tag/v0.7.3). There is an [outstanding issue](https://github.com/facebook/relay/issues/1034) (with a [matching PR]( https://github.com/facebook/relay/pull/1036)) for allowing [facebook/react-relay](https://github.com/facebook/relay) to allow for React v15 as a peer dependency. This will need to be updated too.

facebook/relay#1034
facebook/relay#1036

**Comment by zpao** [comment]
Fixed in #3
