### ISSUE TITLE
React 16.0.0 compatibility

### ISSUE THREAD

**Issue by zunder** [reactjs/react-static-container#5]
Any chance of allowing peerDependencies for `react` version `^16.0.0-alpha.12`? Reason for that is that `react-native` is having this dependency from version `0.43.0`, which has very desirable features.

**Comment by schingeldi** [comment]
+1

**Comment by Qolzam** [comment]
same issue

**Comment by orangecoloured** [comment]
+1

**Comment by mindhivefi** [comment]
+1 

@matAlmeida 's pull request does not brake anything, but it will resolve many things. Please accept the change :)

**Comment by zpao** [comment]
#6 was landed and I just shipped v1.0.2
